import type { EmailService } from './interfaces'

class InMemoryEmailService implements EmailService {
  private emailLogs: Array<{
    type: string
    to: string
    subject: string
    content: string
    timestamp: Date
    status: 'sent' | 'failed'
  }> = []

  async sendWelcomeEmail(email: string, name?: string): Promise<void> {
    const subject = 'Welcome to PayTracker!'
    const content = this.generateWelcomeEmailContent(email, name)
    
    console.log('📧 [MOCK EMAIL] Sending welcome email to:', email)
    console.log('Subject:', subject)
    console.log('Content:', content)
    
    // Simulate email sending delay
    await this.simulateEmailSending()
    
    this.logEmail('welcome', email, subject, content, 'sent')
  }

  async sendPasswordResetEmail(email: string, resetToken: string): Promise<void> {
    const subject = 'Reset your PayTracker password'
    const content = this.generatePasswordResetEmailContent(email, resetToken)
    
    console.log('📧 [MOCK EMAIL] Sending password reset email to:', email)
    console.log('Subject:', subject)
    console.log('Reset Token:', resetToken)
    
    await this.simulateEmailSending()
    
    this.logEmail('password-reset', email, subject, content, 'sent')
  }

  async sendBillReminderEmail(email: string, billName: string, amount: number, dueDate: Date): Promise<void> {
    const subject = `Reminder: ${billName} due soon`
    const content = this.generateBillReminderEmailContent(billName, amount, dueDate)
    
    console.log('📧 [MOCK EMAIL] Sending bill reminder to:', email)
    console.log('Subject:', subject)
    console.log('Bill:', billName, 'Amount:', amount, 'Due:', dueDate.toDateString())
    
    await this.simulateEmailSending()
    
    this.logEmail('bill-reminder', email, subject, content, 'sent')
  }

  async sendTestEmail(email: string): Promise<void> {
    const subject = 'Test Email from PayTracker'
    const content = this.generateTestEmailContent(email)
    
    // Server-side logging (shows in Node terminal)
    console.log('\n🚀 [SERVER] Test Email Request')
    console.log('=================================')
    console.log(`📧 To: ${email}`)
    console.log(`📋 Subject: ${subject}`)
    console.log(`⏰ Time: ${new Date().toLocaleString()}`)
    console.log('=================================\n')
    
    // Client-side logging (shows in browser console)
    console.log('📧 [MOCK EMAIL] Sending test email to:', email)
    console.log('Subject:', subject)
    console.log('Content:')
    console.log('----------------------------------------')
    console.log(content)
    console.log('----------------------------------------')
    
    await this.simulateEmailSending()
    
    this.logEmail('test', email, subject, content, 'sent')
    
    // Final server confirmation
    console.log('✅ [SERVER] Test email completed successfully!\n')
  }

  // Helper methods
  private async simulateEmailSending(): Promise<void> {
    // Simulate network delay
    await new Promise(resolve => setTimeout(resolve, 100 + Math.random() * 200))
  }

  private logEmail(type: string, to: string, subject: string, content: string, status: 'sent' | 'failed'): void {
    this.emailLogs.push({
      type,
      to,
      subject,
      content,
      timestamp: new Date(),
      status
    })
  }

  private generateWelcomeEmailContent(email: string, name?: string): string {
    const displayName = name || email.split('@')[0]
    
    return `
Hello ${displayName}!

Welcome to PayTracker - your new favorite tool for staying on top of bill payments!

🎉 Your account has been successfully created.

Here's what you can do now:
• Add all your upcoming bills
• Visualize your cash flow on our calendar
• Set up email reminders so you never miss a payment
• Track your safe zones and danger periods

Ready to get started? Log in to your account and add your first bill!

Best regards,
The PayTracker Team

---
This is a mock email generated by PayTracker's development environment.
In production, this would be sent via a real email service like SendGrid or AWS SES.
    `.trim()
  }

  private generateTestEmailContent(email: string): string {
    return `
Hello!

This is a test email from PayTracker to verify that your email functionality is working correctly.

Your account email: ${email}
Test sent at: ${new Date().toLocaleString()}

If you received this test, your email settings are configured properly!

Best regards,
The PayTracker Team

---
This is a mock email generated by PayTracker's development environment.
In production, this would be sent via a real email service like SendGrid or AWS SES.
    `.trim()
  }

  private generatePasswordResetEmailContent(email: string, resetToken: string): string {
    return `
Hello!

We received a request to reset your PayTracker password.

Reset Token: ${resetToken}

If you didn't request this password reset, please ignore this email.

Best regards,
The PayTracker Team

---
This is a mock email generated by PayTracker's development environment.
    `.trim()
  }

  private generateBillReminderEmailContent(billName: string, amount: number, dueDate: Date): string {
    const formattedAmount = new Intl.NumberFormat('en-PH', {
      style: 'currency',
      currency: 'PHP'
    }).format(amount)
    
    const formattedDate = dueDate.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })

    return `
📅 BILL REMINDER

Hi there!

This is a friendly reminder that your ${billName} payment is coming up soon.

Amount: ${formattedAmount}
Due Date: ${formattedDate}

Don't forget to make your payment to avoid any late fees!

You can log in to PayTracker to view all your upcoming bills and manage your reminders.

Best regards,
The PayTracker Team

---
This is a mock email generated by PayTracker's development environment.
    `.trim()
  }

  // Development helper methods
  getEmailLogs(): typeof this.emailLogs {
    return [...this.emailLogs]
  }

  clearEmailLogs(): void {
    this.emailLogs = []
  }

  getEmailLogsByType(type: string): typeof this.emailLogs {
    return this.emailLogs.filter(log => log.type === type)
  }
}

export const emailService = new InMemoryEmailService()